title: Tom's Course 2026
author: Thomas J. Sargent & John Stachurski
logo: _static/qe-logo-large.png
description: This website presents a set of lectures on quantitative economic modeling for Tom's 2026 course.

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

execute:
  execute_notebooks: "cache"
  timeout: 7200   # 2 Hours

bibtex_bibfiles:
   - _static/quant-econ.bib

html:
  baseurl: https://2026-tom-course.quantecon.org/

latex:
   latex_documents:
      targetname: 2026-tom-course.tex

sphinx:
  extra_extensions: [sphinx_multitoc_numbering, sphinxext.rediraffe, sphinx_tojupyter, sphinx_exercise, sphinx_togglebutton, sphinx_proof, sphinx.ext.intersphinx]
  config:
    bibtex_reference_style: author_year
    intersphinx_mapping: 
      intro: 
        - "https://intro.quantecon.org/"
        - null
      intermediate:
        - "https://python.quantecon.org/"
        - null
      advanced:
        - "https://python-advanced.quantecon.org/"
        - null
      jax:
        - "https://jax.quantecon.org/"
        - null
    nb_merge_streams: true
    nb_mime_priority_overrides: [
       # HTML
       ['html', 'application/vnd.jupyter.widget-view+json', 10],
       ['html', 'application/javascript', 20],
       ['html', 'text/html', 30],
       ['html', 'text/latex', 40],
       ['html', 'image/svg+xml', 50],
       ['html', 'image/png', 60],
       ['html', 'image/jpeg', 70],
       ['html', 'text/markdown', 80],
       ['html', 'text/plain', 90],
       # Jupyter Notebooks
       ['jupyter', 'application/vnd.jupyter.widget-view+json', 10],
       ['jupyter', 'application/javascript', 20],
       ['jupyter', 'text/html', 30],
       ['jupyter', 'text/latex', 40],
       ['jupyter', 'image/svg+xml', 50],
       ['jupyter', 'image/png', 60],
       ['jupyter', 'image/jpeg', 70],
       ['jupyter', 'text/markdown', 80],
       ['jupyter', 'text/plain', 90],
       # LaTeX
       ['latex', 'text/latex', 10],
       ['latex', 'application/pdf', 20],
       ['latex', 'image/png', 30],
       ['latex', 'image/jpeg', 40],
       ['latex', 'text/markdown', 50],
       ['latex', 'text/plain', 60],
       ['latex', 'text/html', 70],
       # Link Checker
       ['linkcheck', 'text/plain', 10],
       ['linkcheck', 'text/html', 20],
     ]
    html_favicon: _static/lectures-favicon.ico
    html_theme: quantecon_book_theme
    html_static_path: ['_static']
    html_theme_options:
      authors:
        - name: Thomas J. Sargent
          url: http://www.tomsargent.com/
        - name: John Stachurski
          url: https://johnstachurski.net/
      header_organisation_url: https://quantecon.org
      header_organisation: QuantEcon
      repository_url: https://github.com/QuantEcon/2026-tom-course
      nb_repository_url: https://github.com/QuantEcon/2026-tom-course.notebooks
      path_to_docs: lectures
      twitter: quantecon
      twitter_logo_url: https://assets.quantecon.org/img/qe-twitter-logo.png
      og_logo_url: https://assets.quantecon.org/img/qe-og-logo.png
      description: This website presents a set of lectures on quantitative economic modeling for Tom's 2026 course.
      keywords: Python, QuantEcon, Quantitative Economics, Economics, Sloan, Alfred P. Sloan Foundation, Tom J. Sargent, John Stachurski
      launch_buttons:
        colab_url             : https://colab.research.google.com
    mathjax3_config:
      tex:
        macros:
          "argmax": "arg\\,max"
          "argmin": "arg\\,min"
          "col": "col"
          "Span":  "span"
          "epsilon": "\\varepsilon"
          "EE": "\\mathbb{E}"
          "PP": "\\mathbb{P}"
          "RR": "\\mathbb{R}"
          "NN": "\\mathbb{N}"
          "ZZ": "\\mathbb{Z}"
          "aA": "\\mathcal{A}"
          "bB": "\\mathcal{B}"
          "cC": "\\mathcal{C}"
          "dD": "\\mathcal{D}"
          "eE": "\\mathcal{E}"
          "fF": "\\mathcal{F}"
          "gG": "\\mathcal{G}"
          "hH": "\\mathcal{H}"
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # sphinx-exercise
    exercise_style: "solution_follow_exercise"
    rediraffe_redirects:
      index_toc.md: intro.md
    tojupyter_static_file_path: ["source/_static", "_static"]
    tojupyter_target_html: true
    tojupyter_urlpath: "https://2026-tom-course.quantecon.org/"
    tojupyter_image_urlpath: "https://2026-tom-course.quantecon.org/_static/"
    tojupyter_lang_synonyms: ["ipython", "ipython3", "python"]
    tojupyter_kernels:
      python3:
        kernelspec:
          display_name: "Python"
          language: python3
          name: python3
        file_extension: ".py"
    tojupyter_images_markdown: true
